### ISSUE TITLE
Forgot password page/modal

### ISSUE THREAD

**Issue by sebat2004** [OSU-App-Club/beavbright#27]
Create a form that allows people to enter their email to receive a confirmation email to reset their password.

Functional Requirements:
- Form that has an input for a user email. This could be on a separate page as we have it right now or as a modal

Optional:
- Think about how to link to a reset password page that the user can click on from the sent email while ensuring that it was only clicked from the email (the answer is probably easy to find online but might be a cool thought exercise)

No need to implement the actual emailing logic for now (we will likely use a third party service)

**Comment by Nyumat** [comment]
Not needed, we don't support passwords anymore.
